//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGDM_CFE.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Assignment
    {
        public int IdAssignment { get; set; }
        public System.DateTime AssignmentDate { get; set; }
        public Nullable<System.DateTime> ReturnDate { get; set; }
        public int IdEmployee { get; set; }
        public int IdAssignmentState { get; set; }
        public Nullable<int> IdReturnState { get; set; }
    
        public virtual State State { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual State State1 { get; set; }
    }
}
