//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGDM_CFE.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Device
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Device()
        {
            this.MobileDevices = new HashSet<MobileDevice>();
            this.OpticalReaders = new HashSet<OpticalReader>();
            this.States = new HashSet<State>();
        }
    
        public int IdDevice { get; set; }
        public string InventoryNumber { get; set; }
        public string SerialNumber { get; set; }
        public bool IsCriticalMission { get; set; }
        public string Notes { get; set; }
        public bool IsDeleted { get; set; }
        public int IdBusinessProcess { get; set; }
        public int IdCostCenter { get; set; }
        public int IdWorkCenter { get; set; }
    
        public virtual BusinessProcess BusinessProcess { get; set; }
        public virtual CostCenter CostCenter { get; set; }
        public virtual WorkCenter WorkCenter { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MobileDevice> MobileDevices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OpticalReader> OpticalReaders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<State> States { get; set; }
    }
}
