using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Style", "IDE0028:Simplificar la inicialización de la recopilación", Justification = "<pendiente>", Scope = "member", Target = "~P:SGDM_CFE.Model.Models.Area.WorkCenters")]
[assembly: SuppressMessage("Style", "IDE0028:Simplificar la inicialización de la recopilación", Justification = "<pendiente>", Scope = "member", Target = "~P:SGDM_CFE.Model.Models.CostCenter.WorkCenterCostCenters")]
[assembly: SuppressMessage("Style", "IDE0028:Simplificar la inicialización de la recopilación", Justification = "<pendiente>", Scope = "member", Target = "~P:SGDM_CFE.Model.Models.Device.MobileDevices")]
[assembly: SuppressMessage("Style", "IDE0028:Simplificar la inicialización de la recopilación", Justification = "<pendiente>", Scope = "member", Target = "~P:SGDM_CFE.Model.Models.Device.OpticalReaders")]
[assembly: SuppressMessage("Style", "IDE0028:Simplificar la inicialización de la recopilación", Justification = "<pendiente>", Scope = "member", Target = "~P:SGDM_CFE.Model.Models.Device.States")]
[assembly: SuppressMessage("Style", "IDE0028:Simplificar la inicialización de la recopilación", Justification = "<pendiente>", Scope = "member", Target = "~P:SGDM_CFE.Model.Models.Employee.Assignments")]
[assembly: SuppressMessage("Style", "IDE0028:Simplificar la inicialización de la recopilación", Justification = "<pendiente>", Scope = "member", Target = "~P:SGDM_CFE.Model.Models.Role.Users")]
[assembly: SuppressMessage("Style", "IDE0028:Simplificar la inicialización de la recopilación", Justification = "<pendiente>", Scope = "member", Target = "~P:SGDM_CFE.Model.Models.State.AssignmentStateAssignments")]
[assembly: SuppressMessage("Style", "IDE0028:Simplificar la inicialización de la recopilación", Justification = "<pendiente>", Scope = "member", Target = "~P:SGDM_CFE.Model.Models.State.ReturnStateAssignments")]
[assembly: SuppressMessage("Style", "IDE0028:Simplificar la inicialización de la recopilación", Justification = "<pendiente>", Scope = "member", Target = "~P:SGDM_CFE.Model.Models.SIMCard.MobileDevices")]
[assembly: SuppressMessage("Style", "IDE0028:Simplificar la inicialización de la recopilación", Justification = "<pendiente>", Scope = "member", Target = "~P:SGDM_CFE.Model.Models.Type.MobileDevices")]
[assembly: SuppressMessage("Style", "IDE0028:Simplificar la inicialización de la recopilación", Justification = "<pendiente>", Scope = "member", Target = "~P:SGDM_CFE.Model.Models.User.Employees")]
[assembly: SuppressMessage("Style", "IDE0028:Simplificar la inicialización de la recopilación", Justification = "<pendiente>", Scope = "member", Target = "~P:SGDM_CFE.Model.Models.WorkCenter.Devices")]
[assembly: SuppressMessage("Style", "IDE0028:Simplificar la inicialización de la recopilación", Justification = "<pendiente>", Scope = "member", Target = "~P:SGDM_CFE.Model.Models.WorkCenter.WorkCenterBusinessProcesses")]
[assembly: SuppressMessage("Style", "IDE0028:Simplificar la inicialización de la recopilación", Justification = "<pendiente>", Scope = "member", Target = "~P:SGDM_CFE.Model.Models.WorkCenter.WorkCenterCostCenters")]
[assembly: SuppressMessage("Style", "IDE0028:Simplificar la inicialización de la recopilación", Justification = "<pendiente>", Scope = "member", Target = "~P:SGDM_CFE.Model.Models.WorkCenterBusinessProcess.States")]
[assembly: SuppressMessage("Style", "IDE0028:Simplificar la inicialización de la recopilación", Justification = "<pendiente>", Scope = "member", Target = "~P:SGDM_CFE.Model.Models.WorkCenterCostCenter.States")]