//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGDM_CFE.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MobileDevice
    {
        public int IdMobileDevice { get; set; }
        public bool IsDeleted { get; set; }
        public int IdType { get; set; }
        public int IdDevice { get; set; }
        public Nullable<int> IdSIMCard { get; set; }
    
        public virtual Device Device { get; set; }
        public virtual SIMCard SIMCard { get; set; }
        public virtual Type Type { get; set; }
    }
}
