//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGDM_CFE.UI.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SGDM_CFE.UI.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aceptar.
        /// </summary>
        public static string AcceptButton {
            get {
                return ResourceManager.GetString("AcceptButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Zona.
        /// </summary>
        public static string AreaTextColumn {
            get {
                return ResourceManager.GetString("AreaTextColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancelar.
        /// </summary>
        public static string CancelButton {
            get {
                return ResourceManager.GetString("CancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Código.
        /// </summary>
        public static string CodeTextColumn {
            get {
                return ResourceManager.GetString("CodeTextColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se pudo establecer una conexión con el servidor. Por favor, intenta nuevamente más tarde..
        /// </summary>
        public static string ConnectionErrorMessage {
            get {
                return ResourceManager.GetString("ConnectionErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error de conexión.
        /// </summary>
        public static string ConnectionErrorWindowTitle {
            get {
                return ResourceManager.GetString("ConnectionErrorWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear nueva.
        /// </summary>
        public static string CreateNewFemaleButton {
            get {
                return ResourceManager.GetString("CreateNewFemaleButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear nuevo.
        /// </summary>
        public static string CreateNewMaleButton {
            get {
                return ResourceManager.GetString("CreateNewMaleButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear usuario.
        /// </summary>
        public static string CreateUserButton {
            get {
                return ResourceManager.GetString("CreateUserButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminar.
        /// </summary>
        public static string DeleteButton {
            get {
                return ResourceManager.GetString("DeleteButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editar.
        /// </summary>
        public static string EditButton {
            get {
                return ResourceManager.GetString("EditButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Empleados.
        /// </summary>
        public static string EmployeesButton {
            get {
                return ResourceManager.GetString("EmployeesButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Por favor, completa todos los campos obligatorios..
        /// </summary>
        public static string EmptyFieldsMessage {
            get {
                return ResourceManager.GetString("EmptyFieldsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Campos vacíos.
        /// </summary>
        public static string EmptyFieldsWindowTitle {
            get {
                return ResourceManager.GetString("EmptyFieldsWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Olvidaste tu contraseña?.
        /// </summary>
        public static string ForgotPasswordLabel {
            get {
                return ResourceManager.GetString("ForgotPasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sistema para la Gestión de Dispositivos Móviles (SGDM-CFE).
        /// </summary>
        public static string GeneralWindowTitle {
            get {
                return ResourceManager.GetString("GeneralWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La información proporcionada es incorrecta. Por favor, verifica los datos e intenta nuevamente..
        /// </summary>
        public static string InvalidInformationMessage {
            get {
                return ResourceManager.GetString("InvalidInformationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Información incorrecta.
        /// </summary>
        public static string InvalidInformationWindowTitle {
            get {
                return ResourceManager.GetString("InvalidInformationWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Número de inventario.
        /// </summary>
        public static string InventoryNumberTextColumn {
            get {
                return ResourceManager.GetString("InventoryNumberTextColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Iniciar sesión.
        /// </summary>
        public static string LoginButton {
            get {
                return ResourceManager.GetString("LoginButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cerrar sesión.
        /// </summary>
        public static string LogoutButton {
            get {
                return ResourceManager.GetString("LogoutButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Apellido materno:.
        /// </summary>
        public static string MaternalSurnameLabel {
            get {
                return ResourceManager.GetString("MaternalSurnameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Apellido materno.
        /// </summary>
        public static string MaternalSurnameTextColumn {
            get {
                return ResourceManager.GetString("MaternalSurnameTextColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Menú.
        /// </summary>
        public static string MenuTextBlock {
            get {
                return ResourceManager.GetString("MenuTextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre:.
        /// </summary>
        public static string NameLabel {
            get {
                return ResourceManager.GetString("NameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre.
        /// </summary>
        public static string NameTextColumn {
            get {
                return ResourceManager.GetString("NameTextColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lectores ópticos.
        /// </summary>
        public static string OpticalReadersButton {
            get {
                return ResourceManager.GetString("OpticalReadersButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña:.
        /// </summary>
        public static string PasswordLabel {
            get {
                return ResourceManager.GetString("PasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Apellido paterno:.
        /// </summary>
        public static string PaternalSurnameLabel {
            get {
                return ResourceManager.GetString("PaternalSurnameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Apellido paterno.
        /// </summary>
        public static string PaternalSurnameTextColumn {
            get {
                return ResourceManager.GetString("PaternalSurnameTextColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Terminales portátiles.
        /// </summary>
        public static string PortableTerminalsButton {
            get {
                return ResourceManager.GetString("PortableTerminalsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registro Personal del Empleado (RPE):.
        /// </summary>
        public static string RPELabel {
            get {
                return ResourceManager.GetString("RPELabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a RPE.
        /// </summary>
        public static string RPETextColumn {
            get {
                return ResourceManager.GetString("RPETextColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Buscar....
        /// </summary>
        public static string SearchTextBlock {
            get {
                return ResourceManager.GetString("SearchTextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Número de serie.
        /// </summary>
        public static string SerialNumberTextColumn {
            get {
                return ResourceManager.GetString("SerialNumberTextColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tarjetas SIM.
        /// </summary>
        public static string SIMCardsButton {
            get {
                return ResourceManager.GetString("SIMCardsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Panel de inicio.
        /// </summary>
        public static string StartPanelButton {
            get {
                return ResourceManager.GetString("StartPanelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tabletas.
        /// </summary>
        public static string TabletsButton {
            get {
                return ResourceManager.GetString("TabletsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ver detalles.
        /// </summary>
        public static string ViewDetailsButton {
            get {
                return ResourceManager.GetString("ViewDetailsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Centros de trabajo.
        /// </summary>
        public static string WorkCentersButton {
            get {
                return ResourceManager.GetString("WorkCentersButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Centro de trabajo.
        /// </summary>
        public static string WorkCenterTextColumn {
            get {
                return ResourceManager.GetString("WorkCenterTextColumn", resourceCulture);
            }
        }
    }
}
