//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGDM_CFE.UI.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SGDM_CFE.UI.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aceptar.
        /// </summary>
        public static string AcceptButton {
            get {
                return ResourceManager.GetString("AcceptButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No tienes los permisos necesarios para acceder al sistema. Contacta al administrador si necesita asistencia..
        /// </summary>
        public static string AccessDeniedMessage {
            get {
                return ResourceManager.GetString("AccessDeniedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Acceso denegado.
        /// </summary>
        public static string AccessDeniedWindowTitle {
            get {
                return ResourceManager.GetString("AccessDeniedWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Zona:*.
        /// </summary>
        public static string AreaLabel {
            get {
                return ResourceManager.GetString("AreaLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Zona.
        /// </summary>
        public static string AreaTextColumn {
            get {
                return ResourceManager.GetString("AreaTextColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha de asignación.
        /// </summary>
        public static string AssignmentDateTextColumn {
            get {
                return ResourceManager.GetString("AssignmentDateTextColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Asignaciones.
        /// </summary>
        public static string AssignmentsLabel {
            get {
                return ResourceManager.GetString("AssignmentsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Procesos de negocio:*.
        /// </summary>
        public static string BusinessProcessesLabel {
            get {
                return ResourceManager.GetString("BusinessProcessesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Proceso de negocio:.
        /// </summary>
        public static string BusinessProcessLabel {
            get {
                return ResourceManager.GetString("BusinessProcessLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancelar.
        /// </summary>
        public static string CancelButton {
            get {
                return ResourceManager.GetString("CancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Código:*.
        /// </summary>
        public static string CodeLabel {
            get {
                return ResourceManager.GetString("CodeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Código.
        /// </summary>
        public static string CodeTextColumn {
            get {
                return ResourceManager.GetString("CodeTextColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se pudo establecer una conexión con el servidor. Por favor, intenta nuevamente más tarde..
        /// </summary>
        public static string ConnectionErrorMessage {
            get {
                return ResourceManager.GetString("ConnectionErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error de conexión.
        /// </summary>
        public static string ConnectionErrorWindowTitle {
            get {
                return ResourceManager.GetString("ConnectionErrorWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Centro de costos:*.
        /// </summary>
        public static string CostCenterLabel {
            get {
                return ResourceManager.GetString("CostCenterLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Centros de costos:*.
        /// </summary>
        public static string CostCentersLabel {
            get {
                return ResourceManager.GetString("CostCentersLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear empleado.
        /// </summary>
        public static string CreateEmployeeWindowTitle {
            get {
                return ResourceManager.GetString("CreateEmployeeWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear nueva.
        /// </summary>
        public static string CreateNewFemaleButton {
            get {
                return ResourceManager.GetString("CreateNewFemaleButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear nuevo.
        /// </summary>
        public static string CreateNewMaleButton {
            get {
                return ResourceManager.GetString("CreateNewMaleButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear tarjeta SIM.
        /// </summary>
        public static string CreateSIMCardWindowTitle {
            get {
                return ResourceManager.GetString("CreateSIMCardWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear usuario.
        /// </summary>
        public static string CreateUserButton {
            get {
                return ResourceManager.GetString("CreateUserButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear usuario.
        /// </summary>
        public static string CreateUserWindowTitle {
            get {
                return ResourceManager.GetString("CreateUserWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear.
        /// </summary>
        public static string CreateWindowTitle {
            get {
                return ResourceManager.GetString("CreateWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear centro de trabajo.
        /// </summary>
        public static string CreateWorkCenterWindowTitle {
            get {
                return ResourceManager.GetString("CreateWorkCenterWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminar.
        /// </summary>
        public static string DeleteButton {
            get {
                return ResourceManager.GetString("DeleteButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Empleado asignado al equipo:.
        /// </summary>
        public static string DeviceAssignedEmployeeLabel {
            get {
                return ResourceManager.GetString("DeviceAssignedEmployeeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estado del equipo:.
        /// </summary>
        public static string DeviceStateLabel {
            get {
                return ResourceManager.GetString("DeviceStateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editar.
        /// </summary>
        public static string EditButton {
            get {
                return ResourceManager.GetString("EditButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editar empleado.
        /// </summary>
        public static string EditEmployeeWindowTitle {
            get {
                return ResourceManager.GetString("EditEmployeeWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editar tarjeta SIM.
        /// </summary>
        public static string EditSIMCardWindowTitle {
            get {
                return ResourceManager.GetString("EditSIMCardWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editar.
        /// </summary>
        public static string EditWindowTitle {
            get {
                return ResourceManager.GetString("EditWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editar centro de trabajo.
        /// </summary>
        public static string EditWorkCenterWindowTitle {
            get {
                return ResourceManager.GetString("EditWorkCenterWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Correo electrónico:*.
        /// </summary>
        public static string EmailLabel {
            get {
                return ResourceManager.GetString("EmailLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Equipos asignados al empleado:.
        /// </summary>
        public static string EmployeeAssignedDevicesLabel {
            get {
                return ResourceManager.GetString("EmployeeAssignedDevicesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Empleados.
        /// </summary>
        public static string EmployeesButton {
            get {
                return ResourceManager.GetString("EmployeesButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Empleados.
        /// </summary>
        public static string EmployeesLabel {
            get {
                return ResourceManager.GetString("EmployeesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Por favor, completa todos los campos obligatorios..
        /// </summary>
        public static string EmptyFieldsMessage {
            get {
                return ResourceManager.GetString("EmptyFieldsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Campos vacíos.
        /// </summary>
        public static string EmptyFieldsWindowTitle {
            get {
                return ResourceManager.GetString("EmptyFieldsWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descripción de la falla:.
        /// </summary>
        public static string FailuresDescriptionLabel {
            get {
                return ResourceManager.GetString("FailuresDescriptionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Campo.
        /// </summary>
        public static string FieldTextColumn {
            get {
                return ResourceManager.GetString("FieldTextColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Olvidaste tu contraseña?.
        /// </summary>
        public static string ForgotPasswordLabel {
            get {
                return ResourceManager.GetString("ForgotPasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sistema para la Gestión de Dispositivos Móviles (SGDM-CFE).
        /// </summary>
        public static string GeneralWindowTitle {
            get {
                return ResourceManager.GetString("GeneralWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Generar reporte.
        /// </summary>
        public static string GenerateReportButton {
            get {
                return ResourceManager.GetString("GenerateReportButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Tiene fallas?:*.
        /// </summary>
        public static string HasFailuresLabel {
            get {
                return ResourceManager.GetString("HasFailuresLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La información proporcionada es incorrecta. Por favor, verifica los datos e intenta nuevamente..
        /// </summary>
        public static string InvalidInformationMessage {
            get {
                return ResourceManager.GetString("InvalidInformationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Información incorrecta.
        /// </summary>
        public static string InvalidInformationWindowTitle {
            get {
                return ResourceManager.GetString("InvalidInformationWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Número de inventario:.
        /// </summary>
        public static string InventoryNumberLabel {
            get {
                return ResourceManager.GetString("InventoryNumberLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Número de inventario.
        /// </summary>
        public static string InventoryNumberTextColumn {
            get {
                return ResourceManager.GetString("InventoryNumberTextColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Es misión crítica?:*.
        /// </summary>
        public static string IsCriticalMissionLabel {
            get {
                return ResourceManager.GetString("IsCriticalMissionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Es funcional?:*.
        /// </summary>
        public static string IsFunctionalLabel {
            get {
                return ResourceManager.GetString("IsFunctionalLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Iniciar sesión.
        /// </summary>
        public static string LoginButton {
            get {
                return ResourceManager.GetString("LoginButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cerrar sesión.
        /// </summary>
        public static string LogoutButton {
            get {
                return ResourceManager.GetString("LogoutButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Apellido materno:*.
        /// </summary>
        public static string MaternalSurnameLabel {
            get {
                return ResourceManager.GetString("MaternalSurnameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Apellido materno.
        /// </summary>
        public static string MaternalSurnameTextColumn {
            get {
                return ResourceManager.GetString("MaternalSurnameTextColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Menú.
        /// </summary>
        public static string MenuTextBlock {
            get {
                return ResourceManager.GetString("MenuTextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre:*.
        /// </summary>
        public static string NameLabel {
            get {
                return ResourceManager.GetString("NameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre.
        /// </summary>
        public static string NameTextColumn {
            get {
                return ResourceManager.GetString("NameTextColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No.
        /// </summary>
        public static string NoLabel {
            get {
                return ResourceManager.GetString("NoLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Por favor, selecciona un registro antes de continuar..
        /// </summary>
        public static string NoSelectionMessage {
            get {
                return ResourceManager.GetString("NoSelectionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ningún registro seleccionado.
        /// </summary>
        public static string NoSelectionWindowTitle {
            get {
                return ResourceManager.GetString("NoSelectionWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Notas:.
        /// </summary>
        public static string NotesLabel {
            get {
                return ResourceManager.GetString("NotesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lectores ópticos.
        /// </summary>
        public static string OpticalReadersButton {
            get {
                return ResourceManager.GetString("OpticalReadersButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lectores ópticos.
        /// </summary>
        public static string OpticalReadersLabel {
            get {
                return ResourceManager.GetString("OpticalReadersLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a lector óptico.
        /// </summary>
        public static string OpticalReaderWindowTitle {
            get {
                return ResourceManager.GetString("OpticalReaderWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirmación de contraseña:*.
        /// </summary>
        public static string PasswordConfirmationLabel {
            get {
                return ResourceManager.GetString("PasswordConfirmationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña:*.
        /// </summary>
        public static string PasswordLabel {
            get {
                return ResourceManager.GetString("PasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Apellido paterno:*.
        /// </summary>
        public static string PaternalSurnameLabel {
            get {
                return ResourceManager.GetString("PaternalSurnameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Apellido paterno.
        /// </summary>
        public static string PaternalSurnameTextColumn {
            get {
                return ResourceManager.GetString("PaternalSurnameTextColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Terminales portátiles.
        /// </summary>
        public static string PortableTerminalsButton {
            get {
                return ResourceManager.GetString("PortableTerminalsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Terminales portátiles.
        /// </summary>
        public static string PortableTerminalsLabel {
            get {
                return ResourceManager.GetString("PortableTerminalsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a terminal portátil.
        /// </summary>
        public static string PortableTerminalWindowTitle {
            get {
                return ResourceManager.GetString("PortableTerminalWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Requiere mantenimiento?:*.
        /// </summary>
        public static string RequiresMaintenanceLabel {
            get {
                return ResourceManager.GetString("RequiresMaintenanceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha de devolución.
        /// </summary>
        public static string ReturnDateTextColumn {
            get {
                return ResourceManager.GetString("ReturnDateTextColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Notas de revisión:.
        /// </summary>
        public static string ReviewNotesLabel {
            get {
                return ResourceManager.GetString("ReviewNotesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Rol:*.
        /// </summary>
        public static string RoleLabel {
            get {
                return ResourceManager.GetString("RoleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registro Personal del Empleado (RPE):*.
        /// </summary>
        public static string RPELabel {
            get {
                return ResourceManager.GetString("RPELabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a RPE.
        /// </summary>
        public static string RPETextColumn {
            get {
                return ResourceManager.GetString("RPETextColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Buscar....
        /// </summary>
        public static string SearchTextBlock {
            get {
                return ResourceManager.GetString("SearchTextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Número de serie:*.
        /// </summary>
        public static string SerialNumberLabel {
            get {
                return ResourceManager.GetString("SerialNumberLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Número de serie.
        /// </summary>
        public static string SerialNumberTextColumn {
            get {
                return ResourceManager.GetString("SerialNumberTextColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Equipo asignado a la tarjeta SIM:.
        /// </summary>
        public static string SIMCardAssignedDeviceLabel {
            get {
                return ResourceManager.GetString("SIMCardAssignedDeviceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tarjetas SIM.
        /// </summary>
        public static string SIMCardsButton {
            get {
                return ResourceManager.GetString("SIMCardsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tarjetas SIM.
        /// </summary>
        public static string SIMCardsLabel {
            get {
                return ResourceManager.GetString("SIMCardsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Panel de inicio.
        /// </summary>
        public static string StartPanelButton {
            get {
                return ResourceManager.GetString("StartPanelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tabletas.
        /// </summary>
        public static string TabletsButton {
            get {
                return ResourceManager.GetString("TabletsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tabletas.
        /// </summary>
        public static string TabletsLabel {
            get {
                return ResourceManager.GetString("TabletsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a tableta.
        /// </summary>
        public static string TabletWindowTitle {
            get {
                return ResourceManager.GetString("TabletWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo.
        /// </summary>
        public static string TypeTextColumn {
            get {
                return ResourceManager.GetString("TypeTextColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Valor.
        /// </summary>
        public static string ValueTextColumn {
            get {
                return ResourceManager.GetString("ValueTextColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Consultar asignación.
        /// </summary>
        public static string ViewAssignmentLabel {
            get {
                return ResourceManager.GetString("ViewAssignmentLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ver detalles.
        /// </summary>
        public static string ViewDetailsButton {
            get {
                return ResourceManager.GetString("ViewDetailsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Consultar empleado.
        /// </summary>
        public static string ViewEmployeeLabel {
            get {
                return ResourceManager.GetString("ViewEmployeeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Consultar lector óptico.
        /// </summary>
        public static string ViewOpticalReaderLabel {
            get {
                return ResourceManager.GetString("ViewOpticalReaderLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Consultar terminal portátil.
        /// </summary>
        public static string ViewPortableTerminalLabel {
            get {
                return ResourceManager.GetString("ViewPortableTerminalLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Consultar tarjeta SIM.
        /// </summary>
        public static string ViewSIMCardLabel {
            get {
                return ResourceManager.GetString("ViewSIMCardLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Consultar tableta.
        /// </summary>
        public static string ViewTabletLabel {
            get {
                return ResourceManager.GetString("ViewTabletLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Consultar centro de trabajo.
        /// </summary>
        public static string ViewWorkCenterLabel {
            get {
                return ResourceManager.GetString("ViewWorkCenterLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Equipos asignados al centro de trabajo:.
        /// </summary>
        public static string WorkCenterAssignedDevicesLabel {
            get {
                return ResourceManager.GetString("WorkCenterAssignedDevicesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Centro de trabajo:*.
        /// </summary>
        public static string WorkCenterLabel {
            get {
                return ResourceManager.GetString("WorkCenterLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Centros de trabajo.
        /// </summary>
        public static string WorkCentersButton {
            get {
                return ResourceManager.GetString("WorkCentersButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Centros de trabajo.
        /// </summary>
        public static string WorkCentersLabel {
            get {
                return ResourceManager.GetString("WorkCentersLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Centro de trabajo.
        /// </summary>
        public static string WorkCenterTextColumn {
            get {
                return ResourceManager.GetString("WorkCenterTextColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sí.
        /// </summary>
        public static string YesLabel {
            get {
                return ResourceManager.GetString("YesLabel", resourceCulture);
            }
        }
    }
}
